server:
  port: 8081

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://avnadmin:[password]@[url]
    username: avnadmin
    password: password
    hikari:
      maximum-pool-size: 20
  config:
    activate:
      on-profile: local

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.tutorial.spring_boot_tutorial

logging:
  file:
    path: "logs"
    name: "spring-boot-turorial"
