server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://avnadmin:[password]@[url]
    username: avnadmin
    password: password
    hikari:
      maximum-pool-size: 20
  config:
    activate:
      on-profile: dev

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.tutorial.spring_boot_tutorial

logging:
  file:
    path: "logs" #TODO: 환경마다 변경 필요
    name: "spring-boot-turorial"
